Главная страница на флексах
htmlacademy-htmlcss/1489759-sedona-30 pull request #11
Opened 2021-02-25 08:10 UTC by Dashulya1

Честно говоря не знаю, что на главной странице на флексах сделать, подвал только на них. Карточки оставила, вроде их лучше на гридах реализовывать.

2021-02-25 18:18 UTC, vovaborisenko requested changes
## с каждым разом верстка все лучше и лучше, молодец!!

2021-02-25 18:18 UTC, vovaborisenko commented on css/style.css
> + .nav-item:first-child {
в 131 строке лишний пробел вначале

2021-02-25 18:18 UTC, vovaborisenko commented on index.html
> +      <div class="map-substrate"></div>
`<div class="map-substrate"></div>` не могу понять для чего тебе этот блок?

2021-02-25 18:18 UTC, vovaborisenko commented on index.html
> +            </svg></a>
для чего здесь ссылки?? при нажатии на них у тебя скролится страница наверх.

2021-02-25 18:18 UTC, vovaborisenko commented on img/icon-checked.svg
> +</svg>
![image](https://user-images.githubusercontent.com/30496847/109197487-1a0ce680-77ae-11eb-9db8-1c5ff7a3f3a0.png)

2021-02-25 18:18 UTC, vovaborisenko commented on css/style.css
> +}
в данном случае не совсем верно использовать :visiter
![image](https://user-images.githubusercontent.com/30496847/109197611-4294e080-77ae-11eb-8acb-58c4ad163144.png)

2021-02-25 18:18 UTC, vovaborisenko commented on css/style.css
> +}
![image](https://user-images.githubusercontent.com/30496847/109197804-84258b80-77ae-11eb-8ffd-db93b671093b.png)

2021-02-27 04:55 UTC, Dashulya1 commented on css/style.css
> + .nav-item:first-child {
исправила

2021-02-27 04:58 UTC, Dashulya1 commented on index.html
> +      <div class="map-substrate"></div>
это я позиционировала карту абсолютно, чтобы под футер загнать. Но, так как карта выпала из потока, футер поехал наверх и прижался к кнопке "Поиск гостиницы", поэтому я временно создала пустой блок с бэкграундом, чтобы удержать футер. В общем я попробую сделать ещё что нибудь, но не уверена, что получится, может двигаюсь не в правильном направлении

2021-02-27 05:04 UTC, Dashulya1 commented on index.html
> +            </svg></a>
этот момент я подсмотрела в чате, там писали, что календарь это ссылка, поэтому сделала временную обертку, а про +/- ,что кнопки должны быть, но я пока не делала их, потому что ячейки выпали из грида

2021-02-27 05:19 UTC, Dashulya1 commented on index.html
> +            </svg></a>
в общем ссылки убрала, пока не знаю, что с +/- делать

2021-02-27 05:22 UTC, Dashulya1 commented on index.html
> +            </svg></a>
ок, убрала, там вроде попап должен потом быть? Я правильно поняла?

2021-02-27 09:11 UTC, Dashulya1 commented on img/icon-checked.svg
> +</svg>
Да, ок, добавлю

2021-02-27 09:27 UTC, Dashulya1 commented on css/style.css
> +}
ой, да точно, это вполне логично)

2021-02-27 09:31 UTC, Dashulya1 commented on css/style.css
> +}
Красиво вышло)

2021-03-01 16:56 UTC, vovaborisenko commented on index.html
> +            </svg></a>
попап или дропдаун 
ссылка всегда ссылается на что-то, например на другую страницу или на какую-то часть страницы.
а кнопка делает что-то: открывает, скрывает, показывает, удаляет, добавляет.
так что календарь точно должен быть кнопкой

2021-03-01 16:57 UTC, vovaborisenko commented on index.html
> +      <div class="map-substrate"></div>
ясно, да можно так сделать

2021-03-01 17:02 UTC, vovaborisenko commented
# все, хорошо)
теперь нужно очень поднажать, чтобы успеть все сделать по программе и успешно сдать проект!

2021-03-02 10:44 UTC, merged