Оформление главной страницы
htmlacademy-htmlcss/1489759-sedona-30 pull request #13
Opened 2021-03-03 09:11 UTC by Dashulya1

2021-03-04 20:52 UTC, vovaborisenko requested changes
Уже на финишной прямой, теперь нужно меня вытерпеть) т.к. будет много правок)

Правки по стайлгайду для главной страницы https://www.figma.com/file/ASeQqd0fG7Ug51ssFdapgv/HTML-1-%2F-%D0%A1%D0%B5%D0%B4%D0%BE%D0%BD%D0%B0?node-id=2395%3A774:
- style.css 405, 530 строка: вместо .button:focus нужно .button:active (:active это именно момент нажатия, а фокус может быть и не в момент нажатия);
- style.css 481 строка: для инпутов при фокусе нужен border;
- style.css 487, 492 строка: цвет иконок должен меняться при непосредственном наведении на них, не на инпут или обертку инпута.
- style.css 988, 922 строка: псевдоселекторы нужно вешать не на svg, а на интерактивные элементы: ссылка, кнопка.

ты наверно заметила, что шрифт с макетом не сходится (в консоли браузера видно, что он не подключен). (сейчас ты пытаешь подключить шрифт `PT Sans Narrow`) тебе нужно найти шрифт `PT Sans`  и подключить именно его. при подключенном шрифте у тебя будут вот такие несостыковки с макетом их нужно поправить:

![image](https://user-images.githubusercontent.com/30496847/110028291-1c3dea80-7d44-11eb-9e4e-36e086c9cbaf.png)

2021-03-06 17:31 UTC, vovaborisenko commented
![image](https://user-images.githubusercontent.com/30496847/110215349-59c48400-7eba-11eb-974a-7b73ecc8a1c6.png)
![image](https://user-images.githubusercontent.com/30496847/110215433-dce5da00-7eba-11eb-9c11-32da96921107.png)

2021-03-06 17:37 UTC, vovaborisenko requested changes

2021-03-06 17:37 UTC, vovaborisenko commented on css/style.css
>  }
пропиши границы именно через border, а ширина границ по макету 2px.

2021-03-06 17:37 UTC, vovaborisenko commented on css/style.css
>  }
здесь излишняя вложенность селекторов, избавься от нее

2021-03-06 19:24 UTC, Dashulya1 commented on css/style.css
>  }
outline все равно пришлось убрать, иначе border не видно

2021-03-06 19:24 UTC, Dashulya1 commented on css/style.css
>  }
ок

2021-03-07 07:19 UTC, vovaborisenko commented
![image](https://user-images.githubusercontent.com/30496847/110232408-8ca85f80-7f2e-11eb-90cb-12c5dab76d62.png)
![image](https://user-images.githubusercontent.com/30496847/110232412-916d1380-7f2e-11eb-925c-656db19778b6.png)

2021-03-08 07:12 UTC, vovaborisenko commented
# Поздравляю с 8 марта!!
## По главной странице пока все!)

2021-03-08 07:12 UTC, merged