Разметка главной страницы
htmlacademy-htmlcss/1489759-sedona-30 pull request #4
Opened 2021-01-23 06:58 UTC by Dashulya1

2021-01-23 09:26 UTC, vovaborisenko requested changes
перед отправкой на проверку - проходи проверку кода на валидаторе https://validator.w3.org/#validate_by_input (это поможет тебе выявить ошибки самостоятельно)

2021-01-23 09:26 UTC, vovaborisenko commented on index.html
> +        <p>#VISITSEDONA<br>тел: +7(495)666-01-66</p>
нужно избавиться от br

телефон нужно сделать в виде ссылки с атрибутом `href="tel:+номер_только_цифры"`

2021-01-23 09:26 UTC, vovaborisenko commented on index.html
> +        <a href="https://htmlacademy.ru">HTML Academy</a>
неверный текст для выделенного блока на скрине:
![image](https://user-images.githubusercontent.com/30496847/105574314-d2d9a300-5d74-11eb-964b-7af3046c2919.png)

2021-01-23 09:26 UTC, vovaborisenko commented on index.html
> +          <!--Здесь будет карта-->
нужно сделать разметку этих блоков. но я еще уточню точно, нужно ли на этом этапе это делать

2021-01-23 09:26 UTC, vovaborisenko commented on index.html
> +        </ul>
этот блок должен находится после первой причины

2021-01-23 09:26 UTC, vovaborisenko commented on index.html
> +          <li><a href="blank.html">гостиницы</a></li>
ссылка `<a href="blank.html">гостиницы</a>` должна вести на страницу каталога

2021-01-23 10:14 UTC, vovaborisenko commented on index.html
> +          <!--Здесь будет карта-->
уточнил: нужно делать

2021-01-28 10:29 UTC, Dashulya1 commented on index.html
> +        <a><img "blank.html" alt="Логотип Седоны"></a>
Поправила

2021-01-28 10:30 UTC, Dashulya1 commented on index.html
> +      <article>Седона-небольшой городок в Аризоне, заслуживающий большего!</article>
Поменяла на картинку

2021-01-28 10:31 UTC, Dashulya1 commented on index.html
> +        </ul>
Тут все сделала одним сплошным списком

2021-01-28 10:33 UTC, Dashulya1 commented on index.html
> +          <li><a href="blank.html">гостиницы</a></li>
Ссылки вроде бы везде где надо добавила и исправила

2021-01-28 14:51 UTC, vovaborisenko commented on index.html
> +          <form method="post" action="https://htmlacademy.ru/intensive/htmlcss">
https://echo.htmlacademy.ru/ - адрес куда нужно отправлять данные из форму

2021-01-28 14:52 UTC, merged

2021-01-28 16:38 UTC, Dashulya1 commented on index.html
> +          <form method="post" action="https://htmlacademy.ru/intensive/htmlcss">
Да, хорошо, внесла изменения