Графика всех страниц
htmlacademy-htmlcss/1489759-sedona-30 pull request #6
Opened 2021-01-30 10:48 UTC by Dashulya1

2021-01-30 20:16 UTC, vovaborisenko requested changes
### контентные изображения вставила правильно, молодец!!

есть правки, которые сделают твой проект лучше:
- логотип академии лучше выгрузить в формат svg, т.к. в фигме это векторное изображение. а карту - в jpg, т.к. это растровое изображение без прозрачного фона.
- favicon.ico - файл, который нужно держать в корне сайта и у него имя должно быть именно "favicon.ico".
- favicon.ico оставь в корне, а остальные фавиконки перенеси в папку img/favicons, чтобы было ясно для чего эти файлы.
- имена файлов картинок пиши маленькими буквами с разделителем - дефис. и имена объединяй общим словом, например: icon-fb.svg, icon-vk.svg, icon-twitter.svg; bg-main.jpg, bg-inner-page.jpg и т.д. В итоге ты будешь знать, не смотря на картинку, для чего она тебе нужна.
- если используешь manifest, тогда нужно создавать этот манифест в виде файла как описано в лайве. (сейчас ты подключаешь файл манифеста manifest.webmanifest, а ткого файла у тебя нет).
- и то что изображно в Shape.png, должно быть в svg.

2021-01-31 09:40 UTC, Dashulya1 commented
- по поводу карты мне не очень понятно.. на лекции было сказано, что мы смотрим на полноцветность изображения. И если там довольно простая цветовая гамма, то мы используем png и прям про карту сказали, что png надо. Просто интересно это важно вообще, там разница в 1 кб в принципе

2021-01-31 21:24 UTC, vovaborisenko commented
- по поводу карты: может сможешь найти в какой момент они говорят о карте. 
да там разница небольшая в размерах (10-15кБ). У меня принцип по экспорту такой: если не нужен прозрачный фон, тогда это jpg.

2021-01-31 21:45 UTC, vovaborisenko commented
- манифест создан - это хорошо, но картинки, которые там указаны не существуют. нужно прописать правильные пути и соответствующие этим картинкам размеры.
- "и то что изображено в Shape.png, должно быть в svg." - это не выполнено. теперь файл переименован на `main-slicer.png`. нужно экспортировать из фигмы в svg.
- и раз уж правки все равно будут, тогда сделаем именование файлов получше: иконки соцсетей, фотографии отелей названы как надо, молодец!! но остальные слишком длинные названия. идем от общего к частному (для чего, что описывает эта картинка и через дефис имя картинки), например: 
  + `main-feature-hamburger.svg` - это иконка, значит имя ей нужно дать `icon-hamburger.svg`;
  + `main-bg-feature1.jpg` - это фон, и не нужно указывать в названии куда его будешь вставлять (лишнее `main`) - `bg-feature-1.jpg`;
  + `inner-page-sort-trangd.svg` - это иконка, значит лучше ее назвать - `icon-arrow-down.svg`.

обычно имена файлов для картинок начитаются с `icon`, `bg` или просто без ничего - например: `user-1.jpg, user-2.jpg`

2021-02-01 09:23 UTC, Dashulya1 commented
Не стала заливать index и catalog, так как уже начала следующий раздел делать, в общем, url-адреса поменяла в контентных изображениях

2021-02-01 19:16 UTC, vovaborisenko commented
# все отлично умничка!!!

2021-02-01 19:16 UTC, merged