Стилизция главной страницы
htmlacademy-htmlcss/1489759-sedona-30 pull request #7
Opened 2021-02-02 05:48 UTC by Dashulya1

Единственное, что не получилось - добавить интерактив иконке академии, сколько бы я не билась с ней

2021-02-02 10:43 UTC, vovaborisenko requested changes
### с большего все верно молодец!!

- вот небольшие несоответствия с макетом (см. скрин ниже):
- ![image](https://user-images.githubusercontent.com/30496847/106578252-60c14500-6550-11eb-8021-52b986ed4fc8.png)

по критериям оценки тоже есть несоответствия:
- нужно придерживаться одной стилизации (критерий Б15 https://up.htmlacademy.ru/htmlcss/30/criteries#b15):
  1. необходимо убрать один общий отступ. как это быстро сделать: нажать ctrl + A (выделится весь текст в документе) и потом нажать Shift + Tab - итог в выделенной области удалится один отступ.
  2. между селектором и `{` или везде убрать пробел, или везде его добавить. (лучше везде добавить).
  3. единообразная последовательность написания свойств. (пример: https://codeguide.academy/html-css.html#css-order).
  4. все коды цвета должны быть в одном регистре (или большие или маленькие буквы) - лучше маленькие.

совет для идеальности кода:
- в конце каждого файла оставляй только одну пустую строку.
- каждый селектор пиши с новой строки (так ты не потеряешь его).

2021-02-02 10:43 UTC, vovaborisenko commented on css/style.css
> +  }
не должно быть глобальных селекторов тега, согласно критерию Д25 https://up.htmlacademy.ru/htmlcss/30/criteries#d25

2021-02-02 10:43 UTC, vovaborisenko commented on index.html
> +            <p class="feature-tagline">седона-не атракцион для туристов, там течет своя жизнь</p></li>
`</li>` - нужно перенести на новую строку

2021-02-02 10:43 UTC, vovaborisenko commented on css/style.css
> +  }
это лучше заменить на это (так ты не скроешь текст от скринридеров) (только порядок css свойств сделай такой как у тебя в проекте, чтобы было единообразие):
```
.visually-hidden {
  clip: rect(0 0 0 0);
  clip-path: inset(50%);
  height: 1px;
  overflow: hidden;
  position: absolute;
  white-space: nowrap;
  width: 1px;
}

2021-02-02 10:43 UTC, vovaborisenko commented on css/style.css
> +  }
для цвета используй переменные

2021-02-02 10:43 UTC, vovaborisenko commented on css/style.css
> +  }
для цвета используй переменные

2021-02-02 10:43 UTC, vovaborisenko commented on css/style.css
> +    background-color: #5496BD;
для цвета используй переменные

2021-02-02 19:22 UTC, Dashulya1 commented on css/style.css
> +  }
все подправила, теперь покрасивее

2021-02-02 19:24 UTC, Dashulya1 commented on index.html
> +            <p class="feature-tagline">седона-не атракцион для туристов, там течет своя жизнь</p></li>
сделано

2021-02-02 19:28 UTC, Dashulya1 commented on css/style.css
> +  }
окей, спасибо, порядок для этих свойств пока не знаю, только текст делала

2021-02-02 19:28 UTC, Dashulya1 commented on css/style.css
> +  }
поменяла

2021-02-02 19:28 UTC, Dashulya1 commented on css/style.css
> +  }
тут тоже поменяла

2021-02-02 19:29 UTC, Dashulya1 commented on css/style.css
> +    background-color: #5496BD;
и здесь

2021-02-03 07:33 UTC, vovaborisenko requested changes
порядок css свойств идеален.
отлично, что делаешь комментарии.
но добавились ошибки:
- несоответствие макету (см. скрин):
![image](https://user-images.githubusercontent.com/30496847/106713209-2cf72580-660b-11eb-911d-864643a886f8.png)

2021-02-03 07:33 UTC, vovaborisenko commented on css/style.css
> +}
здесь селектор не нужно разбивать на строки, т.к. это один селектор. (селекторы разделяются запятыми и их нужно разделять на строки)

2021-02-03 07:33 UTC, vovaborisenko commented on css/style.css
> +}
вот здесь верное разбиение селекторов на строки

2021-02-03 07:33 UTC, vovaborisenko commented on css/style.css
> +}
нужно соблюдать единообразие кода. 
здесь между `}` и новым селектором в 105 строке есть пустая строка, а ниже нет.
необходимо, чтобы или везде были или везде не были пустые строки между `}` и новым селектором. (лучше чтобы везде были пустые строки)

2021-02-03 07:33 UTC, vovaborisenko commented on css/style.css
> +
для идеальности кода:
количество свойств в селекторе будет только увеличиваться, чтобы не запутаться в частях очень длинного кода комментарии обычно пишут так:
```
/* START Заинтересовались? */
.appointment {
  line-height: 24px;
}
.appointment-info {
  font-size: 30px;
  font-weight: 700;
  color: var(--basic-black);
}
/* END Заинтересовались? */

/* START Форма поиска гостиницы */
.popup {
  line-height: 26px;
  font-weight: 700;
}
/* END Форма поиска гостиницы */

```

2021-02-03 13:45 UTC, Dashulya1 commented on css/style.css
> +}
хорошо, поняла

2021-02-03 13:45 UTC, Dashulya1 commented on css/style.css
> +}
окей)

2021-02-03 13:46 UTC, Dashulya1 commented on css/style.css
> +}
эхх, невнимательность..

2021-02-03 13:46 UTC, Dashulya1 commented on css/style.css
> +
расписала

2021-02-03 18:33 UTC, vovaborisenko commented
# теперь все отлично, молодец!!!

2021-02-03 18:33 UTC, merged