Стилизация внутренней страницы
htmlacademy-htmlcss/1489759-sedona-30 pull request #8
Opened 2021-02-05 13:04 UTC by Dashulya1

Не разобралась с текущим состоянием навигационной цепочки, хотя оочень пыталась((

2021-02-06 12:19 UTC, vovaborisenko requested changes
## стили все прописаны верно, молодец

но есть неоднообразие написания кода

2021-02-06 12:19 UTC, vovaborisenko commented on css/style.css
> +/* END Никак не могу заставить заработать */
этот селектор выбирает следующий тег по структуре дерева (соседний).
```
<div class="breadcrumbs-item">
</div>
<input class="input" type="radio" checked>
```
вот для этого инпута этот селектор

2021-02-06 12:19 UTC, vovaborisenko commented on css/style.css
> +}
нужен пробел перед `{`

2021-02-06 12:19 UTC, vovaborisenko commented on css/style.css
> +/* END Никак не могу заставить заработать */
нужен пробел перед `{`

2021-02-06 12:19 UTC, vovaborisenko commented on css/style.css
> +}
нужен пробел перед `{`

2021-02-06 12:19 UTC, vovaborisenko commented on css/style.css
> +}
и в 119 строке тоже нужно это поправить

2021-02-07 05:39 UTC, Dashulya1 commented on css/style.css
> +/* END Никак не могу заставить заработать */
все, разобралась

2021-02-07 05:40 UTC, Dashulya1 commented on css/style.css
> +}
поправила

2021-02-07 05:40 UTC, Dashulya1 commented on css/style.css
> +/* END Никак не могу заставить заработать */
и это поправила

2021-02-07 05:41 UTC, Dashulya1 commented on css/style.css
> +}
здесь тоже

2021-02-07 05:44 UTC, Dashulya1 commented
Не знаю насчет попапа, сложно там все с полями, пока такое решение нашла, не особо рабочее правда)

2021-02-07 16:03 UTC, vovaborisenko commented
с полями чуть позже разберемся

### все сделала, молодец!!!

p.s. не забывай оставлять в конце файла только одну строку не больше

2021-02-07 16:03 UTC, merged