Сетка на гридах для главной страницы
htmlacademy-htmlcss/1489759-sedona-30 pull request #9
Opened 2021-02-10 09:46 UTC by Dashulya1

Потренировалась делать гриды на всем макете, кроме popup

2021-02-10 18:22 UTC, vovaborisenko requested changes
открыл страницу в браузере и удивился почти готовая страница, НО посмотрев код - это что-то с чем-то)))

нам нужен созвон, чтобы я тебе объяснил как правильно делать отступы. я вышел с отпуска, так что могу в любой день, но после 18:00.

а так если не смотреть код, то может сойти) молодец!)

для формы нужно сделать тоже сетку.

2021-02-10 18:22 UTC, vovaborisenko commented on css/style.css
>  }
отступы неправильно заданы: используй или padding, или margin

2021-02-10 18:22 UTC, vovaborisenko commented on css/style.css
> +/* END Grids */
не используй отрицательные марджины

2021-02-10 18:22 UTC, vovaborisenko commented on css/style.css
> +}
здесь точно не нужен грид

2021-02-11 14:04 UTC, Dashulya1 commented on css/style.css
> +  padding: 0px;
Убрала

2021-02-11 14:05 UTC, Dashulya1 commented on css/style.css
> +}
хорошо

2021-02-11 14:06 UTC, Dashulya1 commented on css/style.css
> +}
задала min-height пока

2021-02-11 14:06 UTC, Dashulya1 commented on css/style.css
> +  padding: 0px;
удалила

2021-02-11 14:07 UTC, Dashulya1 commented on css/style.css
> +  height: auto;
убрала

2021-02-11 14:08 UTC, Dashulya1 commented on css/style.css
> +  margin-left: 50px;
удалила

2021-02-11 14:09 UTC, Dashulya1 commented on css/style.css
>  }
поняла

2021-02-11 14:22 UTC, Dashulya1 commented on css/style.css
> +/* END Grids */
хорошо

2021-02-11 14:29 UTC, Dashulya1 commented on css/style.css
> +}
сделала float-ом

2021-02-14 05:50 UTC, vovaborisenko requested changes
### начало страницы очень хорошо сделано, молодец.
но под конец ты, наверно немного подустала)

- посмотри блоки `.from-3` : внутренности сделай чтобы не было и марджинов и падингов;
- аналогично и для `.appointment-info`;
- футер переделаешь после флексов;
- с формой нужно хорошенько посидеть и разобраться. (все label, input, button сделай первыми потомками для тега `form` - будет легче)

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +  max-width: 1200px;
max-width: 1200px; лишнее

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
>  }
нужно соблюдать порядок свойств

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +}
внутренним картинкам этих блоков задай display: block

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +}
марджины нужно обнулить и , соответсвенно, увеличить падинги

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
>  }
если используешь падинги, смотри чтобы марджинов не было, здесь лучше используй марджины

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +}
здесь перемудрила со стилями(немного не логично). также много лишних тегов в верстке появилось.
вот так должна выглядеть сетка
![image](https://user-images.githubusercontent.com/30496847/107869378-7f073900-6e9e-11eb-94d5-563c636c3a6d.png)

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +}
добавь инпутам классы

2021-02-14 05:50 UTC, vovaborisenko commented on css/style.css
> +}
все отступы здесь не нужны все делает сетка

2021-02-14 05:50 UTC, vovaborisenko commented on img/logo.svg
> +<svg width="138" height="70" viewBox="0 0 138 70" fill="none" fill-opacity="0.85" xmlns="http://www.w3.org/2000/svg">
зачем задана прозрачность для лого?

2021-02-14 05:50 UTC, vovaborisenko commented on index.html
>                </label>
тега div внутри label быть не может (проверяй всегда верстку на валидаторе перед коммитами)

2021-02-14 05:50 UTC, vovaborisenko commented on index.html
> -        </div>
всю твою верстку поламало, не хватает закрывающих тегов (тебя бы мог спасти от таких ошибок валидатор)

2021-02-14 05:50 UTC, vovaborisenko commented on index.html
> +        <div class="images" height="509px" width="1200px"></div>
задавать размеры таким образом для дивов совсем не стоит

2021-02-14 10:48 UTC, Dashulya1 commented on css/style.css
> +  max-width: 1200px;
хорошо

2021-02-14 10:50 UTC, Dashulya1 commented on css/style.css
>  }
извини, не замечаю иногда свой беспорядок)

2021-02-14 13:57 UTC, Dashulya1 commented on img/logo.svg
> +<svg width="138" height="70" viewBox="0 0 138 70" fill="none" fill-opacity="0.85" xmlns="http://www.w3.org/2000/svg">
на макете показалось, что лого слегка прозрачное

2021-02-14 13:58 UTC, Dashulya1 commented on index.html
>                </label>
да, хорошо, извини)

2021-02-15 18:02 UTC, Dashulya1 commented on index.html
> -        </div>
завернула в div лейблы)

2021-02-15 18:03 UTC, Dashulya1 commented on index.html
> +        <div class="images" height="509px" width="1200px"></div>
убрала

2021-02-16 05:19 UTC, Dashulya1 commented on css/style.css
> +}
убрала частично, .date-arrival-layout оставила, потому что иначе фраза сдвигается в начало ячейки

2021-02-16 05:20 UTC, Dashulya1 commented on css/style.css
>  }
да, совсем без марджинов не могу реализовать, паддинг убрала

2021-02-16 05:21 UTC, Dashulya1 commented on css/style.css
> +}
да, хорошо

2021-02-16 06:28 UTC, Dashulya1 commented
Честно, так и не смогла реализовать три последние карточки без отступов, что то все у меня рушится тогда, пыталась через гриды сделать, может не так, конечно, надо) поэтому и не получилось.

2021-02-16 16:53 UTC, vovaborisenko reviewed
### хорошо, я приму 
но с формой там тихий ужас... тебе не следовало сразу все делать pixelperfect делая все только отступами. есть много других способов оформлять инпуты иконками.

вернемся к этой форме попозже

2021-02-16 16:54 UTC, merged